### ISSUE TITLE
Cannot have multiple mount entries with mapfile parameters

### ISSUE THREAD

**Issue by swormke** [pdxcat/puppet-module-autofs#19]
If you use the mount command as shown below you encounter the following error:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Concat[/etc/auto.nfs] is already declared in file /etc/puppetlabs/puppet/environments/production/modules/autofs/manifests/mount.pp:31; cannot redeclare at /etc/puppetlabs/puppet/environments/production/modules/autofs/manifests/mount.pp:31 on node

It looks like you endup calling concat twice wit the same $path variable that causes the error.  You have a fix for this in mapfile.pp where you check for the definition of the Concat object.  Added the same fix around the problem code and it seems to be working fine.  I can do a pull request too if you like with the fix.

Here is my use of the mount command
```
class lrs_nfs {
  file { '/nfs':
    ensure => 'directory',
  }

  autofs::mount { '/nfs':
    map => '/etc/auto.nfs',
  }

  autofs::mount { 'testlab':
    map => 'bldr-nfs-1:/farm',
    mapfile => '/etc/auto.nfs',
  }

  autofs::mount { 'testlab/linux-imgs':
    map => 'blds-nfs-1:/farm/linux-imgs',
    mapfile => '/etc/auto.nfs',
  }
}
```

**Comment by blkperl** [comment]
Yep please submit a PR.
